config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :coin_checks 
  root 'coin_checks#home'
  #for routes customize 
  get 'coin_check/home', to: 'application#home'
  get 'coin_check/history', to: 'coin_checks#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin_check.rb
class CoinCheck < ApplicationRecord
end

app/controllers/application_controller.rb
require 'ruby_coincheck_client'
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def home 
    cc = CoincheckClient.new(ENV["API_KEY"], ENV["API_SECRET"])
    response = cc.read_orders
    result = JSON.parse(response.body)
    @orders = result["orders"]
    render html: @orders
  end 

  def cancel_order
    cc = "test"
  end
end

app/controllers/coin_checks_controller.rb
require 'ruby_coincheck_client'
class CoinChecksController < ApplicationController
  before_action :set_coin_check, only: [:show, :edit, :update, :destroy]
  $api_key =  ENV["API_KEY"]
  $api_secret = ENV["API_SECRET"]

  # initial request to coincheck server 
  def initialize
    @cc = CoincheckClient.new($api_key, $api_secret)
  end 

  #home 
  def home 
    # render html: "test"
  end 

  # GET /coin_checks
  # GET /coin_checks.json
  def index
    # cc = CoincheckClient.new($api_key, $api_secret)
    response = @cc.read_orders
    result = JSON.parse(response.body)
    @orders = result["orders"]
    # @coin_checks = CoinCheck.all
  end

  def history
    response = @cc.read_transactions
    result = JSON.parse(response.body)
    @transactions = result["transactions"]
    # render html: @transactions
  end 
  # GET /coin_checks/1
  # GET /coin_checks/1.json
  def show
  end

  # GET /coin_checks/new
  def new
    @coin_check = CoinCheck.new
  end

  # GET /coin_checks/1/edit
  def edit
  end

  # POST /coin_checks
  # POST /coin_checks.json
  def create
    @coin_check = CoinCheck.new(coin_check_params)

    respond_to do |format|
      if @coin_check.save
        format.html { redirect_to @coin_check, notice: 'Coin check was successfully created.' }
        format.json { render :show, status: :created, location: @coin_check }
      else
        format.html { render :new }
        format.json { render json: @coin_check.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coin_checks/1
  # PATCH/PUT /coin_checks/1.json
  def update
    respond_to do |format|
      if @coin_check.update(coin_check_params)
        format.html { redirect_to @coin_check, notice: 'Coin check was successfully updated.' }
        format.json { render :show, status: :ok, location: @coin_check }
      else
        format.html { render :edit }
        format.json { render json: @coin_check.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coin_checks/1
  # DELETE /coin_checks/1.json
  def destroy
    @coin_check.destroy
    respond_to do |format|
      format.html { redirect_to coin_checks_url, notice: 'Coin check was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coin_check
      @coin_check = CoinCheck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coin_check_params
      params.fetch(:coin_check, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coin_checks_helper.rb
module CoinChecksHelper
end

app/views/coin_checks/_form.html.erb
<%= form_for(coin_check) do |f| %>
  <% if coin_check.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coin_check.errors.count, "error") %> prohibited this coin_check from being saved:</h2>

      <ul>
      <% coin_check.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coin_checks/edit.html.erb
<h1>Editing Coin Check</h1>

<%= render 'form', coin_check: @coin_check %>

<%= link_to 'Show', @coin_check %> |
<%= link_to 'Back', coin_checks_path %>

app/views/coin_checks/history.html.erb
<p id="notice"><%= notice %></p>

<h1>Coin Checks</h1>

<table class="table table-hover">
  <thead>
    <tr>
        <td>transaction id </td>
        <td>order id </td>
        <td>fund </td>
        <td>rate</td>
        <td>type</td>
        <td>create</td>
      </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction["id"] %></td>
        <td><%= transaction["order_id"]%></td>
        <td><%= transaction["funds"]%></td>
        <td><%= transaction["rate"]%></td>
        <td><%= transaction["side"]%></td>
        <td><%= transaction["created_at"]%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/coin_checks/home.html.erb
<p id="notice"><%= notice %></p>

<h1>Coin Checks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td>
        <a href="/coin_checks">List Orders</a> show current orders
        </td>
      </tr>
        <td>
        <a href="/coin_check/home">Home</a>
        </td>
      <tr>
      
      </tr>
  </tbody>
</table>

<br>

app/views/coin_checks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coin Checks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order["id"] %></td>
        <td><%= order["order_type"]%></td>
        <td><%= order["rate"]%></td>
        <td><%= order["pair"]%></td>
        <td><%= order["pending_amount"]%></td>
        <td><%= order["created_at"]%></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/coin_checks/new.html.erb
<h1>New Coin Check</h1>

<%= render 'form', coin_check: @coin_check %>

<%= link_to 'Back', coin_checks_path %>

app/views/coin_checks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_coin_check_path(@coin_check) %> |
<%= link_to 'Back', coin_checks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coincheck</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>